services:
  chat-bot-ai:
    image: "${REGISTRY_FQDN}/${IMAGE_NAME}:${IMAGE_TAG}"
    restart: "unless-stopped"
    container_name: chat-bot-ai
    volumes:
      - ${MODELS_DIR}:/home/user/.cache/huggingface
      - ${APP_DATA_DIR}:/app/data
    environment:
      - TELEGRAM_BOT_TOKEN
      - OPENAI_API_KEY
      - HELP_MESSAGE
      - DATABASE_CONNECTION
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
      # Disable tensorflow warnings
      - TF_CPP_MIN_LOG_LEVEL
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # or device_ids: ['0', '3']
              capabilities: [gpu]
#    entrypoint: python3 main.py

    # networks:
    #   - chat_bot_ai

# networks:
#   postgres_ai:
#     name: postgres_ai_net
#   chat_bot_ai:
#     name: chat_bot_ai_net
